#include "socket_option.hpp"

#include <WinSock2.h>
#include <Windows.h>

#define DEFINE_SOCKET_OPTION(L, name, O)  \
	int so_##name ::level  () { return L; } \
	int so_##name ::option () { return O; }


DEFINE_SOCKET_OPTION(SOL_SOCKET, broadcast,						SO_BROADCAST)
DEFINE_SOCKET_OPTION(SOL_SOCKET, conditional_accept,	SO_CONDITIONAL_ACCEPT)
DEFINE_SOCKET_OPTION(SOL_SOCKET, debug,								SO_DEBUG)
DEFINE_SOCKET_OPTION(SOL_SOCKET, dontlinger,					SO_DONTLINGER)
DEFINE_SOCKET_OPTION(SOL_SOCKET, dontroute,						SO_DONTROUTE)
DEFINE_SOCKET_OPTION(SOL_SOCKET, error,								SO_ERROR)
DEFINE_SOCKET_OPTION(SOL_SOCKET, group_priority,			SO_GROUP_PRIORITY)
DEFINE_SOCKET_OPTION(SOL_SOCKET, keepalive,						SO_KEEPALIVE)
DEFINE_SOCKET_OPTION(SOL_SOCKET, linger,							SO_LINGER)
DEFINE_SOCKET_OPTION(SOL_SOCKET, oobinline,						SO_OOBINLINE)
DEFINE_SOCKET_OPTION(SOL_SOCKET, rcvbuf,							SO_RCVBUF)
DEFINE_SOCKET_OPTION(SOL_SOCKET, reuseaddr,						SO_REUSEADDR)
DEFINE_SOCKET_OPTION(SOL_SOCKET, exclusiveaddruse,		SO_EXCLUSIVEADDRUSE)
DEFINE_SOCKET_OPTION(SOL_SOCKET, rcvtimeo,						SO_RCVTIMEO)
DEFINE_SOCKET_OPTION(SOL_SOCKET, sndbuf,							SO_SNDBUF)
DEFINE_SOCKET_OPTION(SOL_SOCKET, sndtimeo,						SO_SNDTIMEO)
DEFINE_SOCKET_OPTION(SOL_SOCKET, acceptconn,					SO_ACCEPTCONN)
DEFINE_SOCKET_OPTION(SOL_SOCKET, rcvlowat,						SO_RCVLOWAT)
DEFINE_SOCKET_OPTION(SOL_SOCKET, sndlowat,						SO_SNDLOWAT)
DEFINE_SOCKET_OPTION(SOL_SOCKET, type,								SO_TYPE)

